# -*- coding: utf-8 -*-
"""EDA-Retail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPEHpqzIxTvqNzT3YE2K1n8k8PR7uGio

#Task #4 : Exploratory Data Analysis - Retail

Implemented By :- KHOLAPURE JIMISH PRAMOD

**Importing Libraries**
"""

#Import all the required Libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt

#Reading the Dataset and printing top 10 entries
df=pd.read_csv("SampleSuperstore.csv")
print("Dataset imported Successfully")
df.head(10)

"""**Exploratory Data Analysis - SampleSuperstore Dataset**"""

df.columns

df.info()

df.isnull().sum()

df.shape

df.describe()

df.nunique()

df.duplicated().sum()

df.drop_duplicates(subset=None,keep='first',inplace=True)
df.duplicated().sum()

"""**Using Seaborn Libraries : Ploting informative statistical Graphics**"""

sns.pairplot(df,height=2.0 , diag_kind = "kde");

plt.figure(figsize=(6, 8))
splot = sns.countplot(x=df['Ship Mode'],order=df['Ship Mode'].value_counts().index,)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.2f'), (p.get_x() + p.get_width() / 2., p.get_height()), ha = 'center', va = 'center', xytext = (0, 10),
                   textcoords = 'offset points')

df['Ship Mode'].value_counts()

plt.figure(figsize=(6, 8))
splot = sns.countplot(x=df['Segment'])
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.2f'), (p.get_x() + p.get_width() / 2., p.get_height()), ha = 'center', va = 'center', xytext = (0, 10),
                   textcoords = 'offset points')

df['Segment'].value_counts()

plt.figure(figsize=(6, 8))
splot = sns.countplot(x=df['Category'], order=df['Category'].value_counts().index)
for p in splot.patches:
    splot.annotate(format(p.get_height(), '.2f'), (p.get_x() + p.get_width() / 2., p.get_height()), ha = 'center', va = 'center', xytext = (0, 10), 
                   textcoords = 'offset points')

df['Category'].value_counts()

sns.countplot(x=df['Sub-Category'] ,  order=df['Sub-Category'].value_counts().index)
plt.xticks(rotation=90);

plt.figure(figsize=(10,10));
sns.countplot(x=df['State'] ,  order=df['State'].value_counts().index)
plt.xticks(rotation=90);

df['State'].value_counts()

plt.figure(figsize=(10,10))
sns.countplot(x='Region',data=df,palette='Set1',order=df['Region'].value_counts().index)

plt.title('Segment wise Sales in each Region')
sns.barplot(x='Region',y='Sales',data=df,hue='Segment',order=df['Region'].value_counts().index,palette='Set2')
plt.xlabel('Region',fontsize=15)
plt.show()

"""**Final Observations :-**

- *California and New York is the most successfull in business*
- *Profit and Sales are maximum in Consumer Segment and Minimum in Home office segment*
- *Profit and Sales are maximum in west region and minimum in South region*
- *Furniture shows less profit whereas technology and Office supplies have higher profit*
"""